/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete;

import javax.swing.JOptionPane;

/**
 *
 * @author pachu
 */
public class EquipoEl extends javax.swing.JFrame {
    private String datos[] = new String[5];
    private String datos1[] = new String[100];
    /**
     * Creates new form ClienteC
     */
    private boolean verCampo = false;
    /**
     * Creates new form EquipoN
     */
    public EquipoEl() {
        initComponents();
        lista.removeAllItems();
        Conexion conx = new Conexion();
        conx.conectar();
        String[] valores = {"clave_equipo"};
        this.datos1=(conx.llenarEquipo(valores));
        for(int i = 0; i<datos1.length; i++){
           if("".equals(datos1[i]) || "y".equals(datos1[i])){
               break;
           }
           else{
               lista.addItem(String.valueOf(datos1[i]));
           }
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lista = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        mar = new javax.swing.JTextField();
        mod = new javax.swing.JTextField();
        pie = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cliente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1295, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel1.setText("Eliminar Equipo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(524, 21, 271, 48);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Clave del equipo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 80, 136, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Modelo del equipo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(470, 440, 151, 22);

        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaActionPerformed(evt);
            }
        });
        getContentPane().add(lista);
        lista.setBounds(630, 80, 85, 41);

        jButton2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 590, 209, 59);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Descripción del equipo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 250, 183, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Marca del equipo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 350, 140, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Cantidad de piezas:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 510, 154, 22);

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(630, 210, 197, 96);
        getContentPane().add(mar);
        mar.setBounds(630, 350, 197, 36);
        getContentPane().add(mod);
        mod.setBounds(630, 430, 197, 36);

        pie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pieKeyPressed(evt);
            }
        });
        getContentPane().add(pie);
        pie.setBounds(630, 510, 197, 38);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Clave del cliente:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(490, 150, 133, 22);

        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clienteKeyPressed(evt);
            }
        });
        getContentPane().add(cliente);
        cliente.setBounds(630, 140, 197, 33);

        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(730, 80, 100, 42);

        jButton3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(660, 590, 214, 59);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        camposC();
        if(this.verCampo){
            Conexion conx = new Conexion();
            conx.conectar();
            int id=Integer.parseInt((String) lista.getSelectedItem());
            int piezas= Integer.parseInt(pie.getText());
            int cliente1= Integer.parseInt(cliente.getText());
            Equipo actualizacion = new Equipo(id, cliente1, desc.getText(), mar.getText(), mod.getText(), piezas);
            conx.modificaEquipo(actualizacion);
            JOptionPane.showMessageDialog(null, "Datos insertados correctamente");
            verCampo=false;
            limpiar();
            conx.desconectar();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pieKeyPressed
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
      if(Character.isLetter(validar)){
        JOptionPane.showMessageDialog(rootPane, "Sólo se pueden ingresar números");
                pie.setText(null);
      }
    }//GEN-LAST:event_pieKeyPressed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_clienteActionPerformed

    private void clienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clienteKeyPressed
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
      if(Character.isLetter(validar)){
        JOptionPane.showMessageDialog(rootPane, "Sólo se pueden ingresar números");
      }
    }//GEN-LAST:event_clienteKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                if(!"".equals(this.lista.getSelectedItem())){
            
            Conexion conx = new Conexion ();
            conx.conectar();
            int id=Integer.parseInt((String) lista.getSelectedItem());
            Equipo equipo = new Equipo(id);
            String[] valores = {"clave_cliente", "descripcion", "marca", "modelo", "piezas"};
            this.datos = (conx.buscaEquipo(equipo, valores));
            this.cliente.setText(this.datos[0]);
            this.desc.setText(this.datos[1]);
            this.mar.setText(this.datos[2]);
            this.mod.setText(this.datos[3]);
            this.pie.setText(this.datos[4]);
}else{
    JOptionPane.showMessageDialog(null, "Por favor ingresa una matricula para poder procesar");
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        camposC();
        if(this.verCampo){
            Conexion conx = new Conexion();
            conx.conectar();
            int id=Integer.parseInt((String) lista.getSelectedItem());
            Equipo eliminacion = new Equipo(id);
            conx.eliminaEquipo(eliminacion);
            JOptionPane.showMessageDialog(null, "Datos eliminados correctamente");
            verCampo=false;
            limpiar();
            conx.desconectar();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cliente;
    private javax.swing.JTextArea desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> lista;
    private javax.swing.JTextField mar;
    private javax.swing.JTextField mod;
    private javax.swing.JTextField pie;
    // End of variables declaration//GEN-END:variables
        public void camposC() {
        if (!"".equals(this.desc.getText()) && !"".equals(this.mar.getText()) && !"".equals(this.mod.getText()) && !"".equals(this.pie.getText())&& !"".equals(this.cliente.getText())) {
            this.verCampo = true;
        } else {
            this.verCampo = false;
            JOptionPane.showMessageDialog(null, "No puede haber campos vacios");

        }
    }
    
    public void limpiar(){
        this.cliente.setText(null);
        this.desc.setText(null);
        this.mar.setText(null);
        this.mod.setText(null);
        this.pie.setText(null);

    }
}
