/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete;

import javax.swing.JOptionPane;

/**
 *
 * @author pachu
 */
public class EquipoN extends javax.swing.JFrame {
    private String datos[] = new String[7];
    private String datos1[] = new String[100];
    /**
     * Creates new form ClienteC
     */
    private boolean verCampo = false;
    /**
     * Creates new form EquipoN
     */
    public EquipoN() {
        initComponents();
        lista.removeAllItems();
        Conexion conx = new Conexion();
        conx.conectar();
        String[] valores = {"clave_cliente"};
        this.datos1=(conx.llenarCliente(valores));
        for(int i = 0; i<datos1.length; i++){
           if("".equals(datos1[i]) || "y".equals(datos1[i])){
               break;
           }
           else{
               lista.addItem(String.valueOf(datos1[i]));
           }
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lista = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        mar = new javax.swing.JTextField();
        mod = new javax.swing.JTextField();
        pie = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1285, 725));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel1.setText("Alta Equipo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(611, 13, 201, 48);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Clave del cliente:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(554, 121, 133, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Modelo del equipo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(536, 409, 151, 22);

        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(lista);
        lista.setBounds(699, 114, 197, 41);

        jButton2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(615, 586, 209, 59);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Descripción del equipo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(504, 222, 183, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Marca del equipo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(547, 327, 140, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Cantidad de piezas:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(533, 487, 154, 22);

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(699, 186, 197, 96);
        getContentPane().add(mar);
        mar.setBounds(699, 322, 197, 36);
        getContentPane().add(mod);
        mod.setBounds(699, 404, 197, 36);

        pie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieActionPerformed(evt);
            }
        });
        pie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pieKeyPressed(evt);
            }
        });
        getContentPane().add(pie);
        pie.setBounds(699, 479, 197, 38);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        camposC();
        if(this.verCampo){
            Conexion conx = new Conexion();
            conx.conectar();
            int id=Integer.parseInt((String) lista.getSelectedItem());
            int id2=Integer.parseInt((String) pie.getText());
            Equipo insercion = new Equipo(id,desc.getText(), mar.getText(), mod.getText(),id2 );
            conx.altaEquipo(insercion);
            JOptionPane.showMessageDialog(null, "Datos insertados correctamente");
            verCampo=false;
            limpiar();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pieKeyPressed
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
      if(Character.isLetter(validar)){
        JOptionPane.showMessageDialog(rootPane, "Sólo se pueden ingresar números");
        pie.setText(null);
      }
    }//GEN-LAST:event_pieKeyPressed

    private void pieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pieActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea desc;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> lista;
    private javax.swing.JTextField mar;
    private javax.swing.JTextField mod;
    private javax.swing.JTextField pie;
    // End of variables declaration//GEN-END:variables
        public void camposC() {
        if (!"".equals(this.desc.getText()) && !"".equals(this.mar.getText()) && !"".equals(this.mod.getText()) && !"".equals(this.pie.getText())) {
            this.verCampo = true;
        } else {
            this.verCampo = false;
            JOptionPane.showMessageDialog(null, "No puede haber campos vacios");

        }
    }
    
    public void limpiar(){
    
        this.desc.setText(null);
        this.mar.setText(null);
        this.mod.setText(null);
        this.pie.setText(null);

    }
}
