/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete;

import javax.swing.JOptionPane;

/**
 *
 * @author pachu
 */
public class nuevaReparacion extends javax.swing.JFrame {
private String datos1[] = new String[100];
private boolean verCampo = false;
    /**
     * Creates new form nuevaReparacion
     */
    public nuevaReparacion() {
        initComponents();
        lista.removeAllItems();
        Conexion conx = new Conexion();
        conx.conectar();
        String[] valores = {"clave_equipo"};
        this.datos1=(conx.llenarEquipo(valores));
        for(int i = 0; i<datos1.length; i++){
           if("".equals(datos1[i]) || "y".equals(datos1[i])){
               break;
           }
           else{
               lista.addItem(String.valueOf(datos1[i]));
           }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lista = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        diag = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        acc = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tipo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dur = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel1.setText("Nueva Reparación");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 26, 316, 48);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Clave del equipo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(436, 126, 136, 22);

        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(lista);
        lista.setBounds(590, 119, 109, 41);

        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jButton1.setText("Nuevo Equipo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(711, 116, 141, 44);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Diagnostico:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(475, 207, 97, 22);

        diag.setColumns(20);
        diag.setRows(5);
        jScrollPane1.setViewportView(diag);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(590, 178, 262, 96);

        acc.setColumns(20);
        acc.setRows(5);
        jScrollPane2.setViewportView(acc);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(590, 305, 262, 96);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Acciones a realizar:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(422, 338, 150, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Duración aproximada de la reparación:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(269, 504, 303, 22);
        getContentPane().add(tipo);
        tipo.setBounds(590, 429, 262, 36);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tipo:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(531, 443, 41, 22);
        getContentPane().add(dur);
        dur.setBounds(590, 499, 262, 36);

        jButton2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 560, 209, 59);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        camposC();
        if(this.verCampo){
            Conexion conx = new Conexion();
            conx.conectar();
            int id=Integer.parseInt((String) lista.getSelectedItem());
            Reparacion insercion = new Reparacion(id, diag.getText(),acc.getText(), tipo.getText(), dur.getText());
            conx.altaReparacion(insercion);
            JOptionPane.showMessageDialog(null, "Datos insertados correctamente");
            verCampo=false;
            limpiar();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new EquipoN().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea acc;
    private javax.swing.JTextArea diag;
    private javax.swing.JTextField dur;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> lista;
    private javax.swing.JTextField tipo;
    // End of variables declaration//GEN-END:variables
    public void camposC() {
        if (!"".equals(this.diag.getText()) && !"".equals(this.acc.getText()) && !"".equals(this.tipo.getText()) && !"".equals(this.dur.getText())) {
            this.verCampo = true;
        } else {
            this.verCampo = false;
            JOptionPane.showMessageDialog(null, "No puede haber campos vacios");

        }
    }
    
    public void limpiar(){
    
        this.diag.setText(null);
        this.acc.setText(null);
        this.tipo.setText(null);
        this.dur.setText(null);

    
    }
}
