/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete;

import javax.swing.JOptionPane;

/**
 *
 * @author pachu
 */
public class PiezaA extends javax.swing.JFrame {
    private String datos[] = new String[2];
    private String datos1[] = new String[100];
    /**
     * Creates new form PiezaN
     */
        private boolean verCampo = false;

    public PiezaA() {
        initComponents();
        lista.removeAllItems();
        Conexion conx = new Conexion();
        conx.conectar();
        String[] valores = {"clave_piezas"};
        this.datos1=(conx.llenarPieza(valores));
        for(int i = 0; i<datos1.length; i++){
           if("".equals(datos1[i]) || "y".equals(datos1[i])){
               break;
           }
           else{
               lista.addItem(String.valueOf(datos1[i]));
           }
        } 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        desc = new javax.swing.JTextField();
        lista = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        eq = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1285, 725));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Id Piezas:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(461, 257, 77, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Descripción de la pieza:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(355, 397, 185, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel1.setText("Nueva Pieza");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(536, 157, 213, 48);

        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(548, 542, 161, 51);
        getContentPane().add(desc);
        desc.setBounds(607, 393, 295, 34);

        lista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(lista);
        lista.setBounds(605, 248, 135, 45);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Id Equipo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(455, 326, 83, 22);
        getContentPane().add(eq);
        eq.setBounds(605, 321, 297, 36);

        jButton2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(758, 245, 144, 45);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        camposC();
        if(this.verCampo){
            Conexion conx = new Conexion();
            conx.conectar();
            int id = Integer.parseInt((String) lista.getSelectedItem());
            int id2= Integer.parseInt(eq.getText());
            Pieza insercion = new Pieza(id, desc.getText(),id2);
            conx.modificaPieza(insercion);
            JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
            verCampo=false;
            limpiar();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                if(!"".equals(this.lista.getSelectedItem())){
            
            Conexion conx = new Conexion ();
            conx.conectar();
            int id=Integer.parseInt((String) lista.getSelectedItem());
            Pieza pieza = new Pieza(id);
            String[] valores = {"nombrepieza", "matricula_equipo"};
            this.datos = (conx.buscaPiezas(pieza, valores));
            this.desc.setText(this.datos[0]);
            this.eq.setText(this.datos[1]);
}else{
    JOptionPane.showMessageDialog(null, "Por favor ingresa una matricula para poder procesar");
}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField desc;
    private javax.swing.JTextField eq;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> lista;
    // End of variables declaration//GEN-END:variables

    public void camposC() {
        if (!"".equals(this.desc.getText()) ) {
            this.verCampo = true;
        } else {
            this.verCampo = false;
            JOptionPane.showMessageDialog(null, "No puede haber campos vacios");

        }
    }
    
    public void limpiar(){   
        this.desc.setText(null);
        this.eq.setText(null);
    }




}
