/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete;

import javax.swing.JOptionPane;


/**
 *
 * @author arman
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public String usuario;
   
    
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        Reparaciones = new javax.swing.JMenu();
        consultaRep = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        dueño = new javax.swing.JMenu();
        crearCliente = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mascota = new javax.swing.JMenu();
        insertarEquipo = new javax.swing.JMenuItem();
        insertarPiezas = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1179, 689));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 242, 128));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Ayuda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 360, 234, 82);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(906, 240, 0, 0);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 23, 0, 0);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 41, 0, 0);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(12, 59, 0, 0);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, -40, 1280, 700);

        barraMenu.setAlignmentX(10.0F);
        barraMenu.setAlignmentY(100.0F);
        barraMenu.setPreferredSize(new java.awt.Dimension(365, 100));

        Reparaciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Reparaciones.setText("Reparaciones");
        Reparaciones.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        consultaRep.setText("Nueva Reparacion");
        consultaRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaRepActionPerformed(evt);
            }
        });
        Reparaciones.add(consultaRep);

        jMenuItem2.setText("Actualizar reparación");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Reparaciones.add(jMenuItem2);

        jMenuItem5.setText("Actualizar estado de una reparación");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Reparaciones.add(jMenuItem5);

        jMenuItem6.setText("Historial de reparaciones");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        Reparaciones.add(jMenuItem6);

        barraMenu.add(Reparaciones);

        dueño.setText("Clientes");
        dueño.setActionCommand("Cliente");
        dueño.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        crearCliente.setText("Crear Cliente");
        crearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearClienteActionPerformed(evt);
            }
        });
        dueño.add(crearCliente);

        jMenuItem1.setText("Actualizar/Consultar un ciente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        dueño.add(jMenuItem1);

        barraMenu.add(dueño);

        mascota.setText("Equipos");
        mascota.setToolTipText("");
        mascota.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        insertarEquipo.setText("Nuevo equipo");
        insertarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarEquipoActionPerformed(evt);
            }
        });
        mascota.add(insertarEquipo);

        insertarPiezas.setText("Nueva Pieza");
        insertarPiezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarPiezasActionPerformed(evt);
            }
        });
        mascota.add(insertarPiezas);

        jMenuItem3.setText("Actualizar equipo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mascota.add(jMenuItem3);

        jMenuItem4.setText("Editar Piezas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mascota.add(jMenuItem4);

        barraMenu.add(mascota);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearClienteActionPerformed
        new ClienteA().setVisible(true);
    }//GEN-LAST:event_crearClienteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       new ClienteC().setVisible(true);

       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Reparaciones: Informacion sobre reparaciones pasadas y piezas usadas \n Clientes:Permite generar nuevos clientes y actualizarlos \n "
                + "Equipos: Permite ingresar un nuevo equipo"
                + "revisar sus piezas usadas y reparaciones");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void consultaRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaRepActionPerformed
        new nuevaReparacion().setVisible(true);
    }//GEN-LAST:event_consultaRepActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new AReparacion().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new ReparacionC().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new ReparacionH().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new PiezaA().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new EquipoA().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void insertarPiezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarPiezasActionPerformed
        new PiezaN().setVisible(true);
    }//GEN-LAST:event_insertarPiezasActionPerformed

    private void insertarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarEquipoActionPerformed
        new EquipoN().setVisible(true);
    }//GEN-LAST:event_insertarEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Reparaciones;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem consultaRep;
    private javax.swing.JMenuItem crearCliente;
    private javax.swing.JMenu dueño;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JMenuItem insertarEquipo;
    private javax.swing.JMenuItem insertarPiezas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu mascota;
    // End of variables declaration//GEN-END:variables


}
