/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author pachu
 */
public class ReparacionH extends javax.swing.JFrame {
private String datos[] = new String[7];
String[] thisIsAStringArray = new String[5];
    /**
     * Creates new form ReparacionC
     */
    public ReparacionH() {
        initComponents();
        mostrar();
    }
    
    String [] valores = {"clave_revision", "clave_equipo", "diagnostico", "acciones", "tipo", "duracion"};
     private void mostrar(){
         DefaultTableModel modelo = new DefaultTableModel();
         ResultSet rs = Conexion.getTabla2("select * from terminada");
         modelo.setColumnIdentifiers(new Object[]{"Clave de revision", "Equipo","Diagnostico", "Acciones","Tipo", "Duracion aproximada" });
         try{
             while(rs.next()){
                    
                    datos[0]=rs.getString(1);
                    datos[1]=rs.getString(2);
                    datos[2]=rs.getString(3);
                    datos[3]=rs.getString(4);
                    datos[4]=rs.getString(5);
                    datos[5]=rs.getString(6);
                    modelo.addRow(datos);

            }
             table.setModel(modelo);
         }catch(Exception e){}
     }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtruta = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        generar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1285, 725));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel1.setText("Reparaciones terminadas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(408, 27, 436, 48);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Clave revision", "Clave equipo", "Diagnostico", "Acciones", "Tipo", "Duracion aproximada"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 93, 1031, 407);

        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        jButton1.setText("Activar reparación");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 536, 317, 127);
        getContentPane().add(txtruta);
        txtruta.setBounds(774, 536, 208, 44);

        jButton2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jButton2.setText("Guardar en...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1000, 536, 151, 44);

        generar.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        generar.setText("Generar reporte");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });
        getContentPane().add(generar);
        generar.setBounds(774, 598, 377, 65);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pdf.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1110, 510, 180, 200);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selecionada;
        DefaultTableModel tabla1;
        Conexion conx = new Conexion();
        conx.conectar();
        selecionada= table.getSelectedRow();

        int id=Integer.parseInt((String) table.getValueAt(selecionada, 0));
        System.out.println(id);
        Reparacion revision = new Reparacion(id);
        conx.moverTabla2(revision);
        tabla1 = (DefaultTableModel) table.getModel();
        tabla1.removeRow(selecionada);
        JOptionPane.showMessageDialog(null, "La reparacion se reactivó");
        conx.desconectar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser dlg = new JFileChooser();
        int option = dlg.showSaveDialog(this);
        if(option == JFileChooser.APPROVE_OPTION){
            File f = dlg.getSelectedFile();
            txtruta.setText(f.toString());    
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
        // TODO add your handling code here:
        String ruta =  txtruta.getText();
        
        try{
            FileOutputStream archivo = new FileOutputStream(ruta+".pdf");
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
           
            doc.add(new Paragraph("------------------------------Reparaciones terminadas-------------------------"));

             for (int i = 0; i < table.getRowCount(); i++) {
                        doc.add(new Paragraph("ID de revision: "+table.getValueAt(i, 0)));
                        doc.add(new Paragraph("Clave de equipo: "+table.getValueAt(i, 1)));
                        doc.add(new Paragraph("Diagnostico: "+table.getValueAt(i, 2)));
                        doc.add(new Paragraph("Acciones: "+table.getValueAt(i, 3)));
                        doc.add(new Paragraph("Tipo: "+table.getValueAt(i, 4)));
                        doc.add(new Paragraph("Duracion aproximada: "+table.getValueAt(i, 5)));
                        doc.add(new Paragraph("---------------------------------------------------"));
            }
            doc.close();
            JOptionPane.showMessageDialog(null, "Archivo creado correctamente en: "+ruta);
        }catch(Exception e){
           e.printStackTrace();
        }
    }//GEN-LAST:event_generarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtruta;
    // End of variables declaration//GEN-END:variables
}
