/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paquete;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author arman
 */
public class Sesion extends javax.swing.JFrame {
    public static String usuario2;
    /**
     * Creates new form Login
     */
    
     
    public Sesion() {
        initComponents();
    }
     private Connection con = null;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        labelUsuario = new javax.swing.JLabel();
        textContraseña = new javax.swing.JPasswordField();
        aceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(593, 503));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        labelTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        labelTitulo.setText("Login");
        getContentPane().add(labelTitulo);
        labelTitulo.setBounds(590, 70, 100, 48);

        labelPassword.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        labelPassword.setText("Password:");
        labelPassword.setOpaque(true);
        getContentPane().add(labelPassword);
        labelPassword.setBounds(460, 370, 110, 40);

        textUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(textUsuario);
        textUsuario.setBounds(580, 310, 190, 40);

        labelUsuario.setFont(new java.awt.Font("Segoe UI Semilight", 0, 24)); // NOI18N
        labelUsuario.setText("Usuario:");
        labelUsuario.setOpaque(true);
        getContentPane().add(labelUsuario);
        labelUsuario.setBounds(460, 310, 110, 40);
        getContentPane().add(textContraseña);
        textContraseña.setBounds(580, 370, 190, 40);

        aceptar.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar);
        aceptar.setBounds(560, 480, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/log.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 100, 210, 230);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 160, 1280, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuarioActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
      
        if("".equals(this.textUsuario.getText()) || "".equals(this.textContraseña.getText()) ){
            //mensaje de excepcion
                JOptionPane.showMessageDialog(null, "Hay campos vacios");
        }else{
                try {
                    String usuario= textUsuario.getText();
                    usuario2= textUsuario.getText();
                conectar(usuario);
            } catch (SQLException ex) {
                Logger.getLogger(Sesion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPasswordField textContraseña;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables

private void conectar(String usuario) throws SQLException {
        try{
        
            Class.forName("com.mysql.jdbc.Driver");
            
            con = DriverManager.getConnection("jdbc:mysql://177.224.17.164/pizzas?user="+usuario+"&password=");
            System.out.println("Conectado weeee");
            if(con!= null){
                PrincipalA vista = new PrincipalA();
                vista.setVisible(true);
                this.dispose();
            }
            
        }catch(ClassNotFoundException cnfe){
            System.out.println(cnfe.getMessage());
        
        }catch(SQLException sqle){
            System.out.println(sqle.getMessage());
        
        }
       
    }
}
